# Generated by Django 5.1.4 on 2025-03-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
